#define TEXTURE_ATLAS_PATH "src/engine/render/assets/textureatlas2.png"
#define TEXTURE_ATLAS_TILE_WIDTH 12
#define TEXTURE_ATLAS_TILE_HEIGHT 11

#define SCREEN_WIDTH 600.0f
#define SCREEN_HEIGHT 400.0f

#define ORTHO_DIVISOR 50.f

#define ORTHO_WIDTH SCREEN_WIDTH / ORTHO_DIVISOR
#define ORTHO_HEIGHT SCREEN_HEIGHT / ORTHO_DIVISOR

#define MATH_DEG2RAD 0.0174533f